### PR TITLE
fix: fix unknown sender address

### LINKED ISSUE #3862: [Task] Sender is always unknown for incoming transactions

### PR DESCRIPTION
**Pull request by MarkNerdi**
## Summary
Now correctly uses the sender/recipient to determine the subject

## Changelog

```
- fix wrong reference in constructor
- sync balance if activity is claimed
```

## Relevant Issues

Closes #3862 

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [x] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/lib/core/wallet/actions/claimActivity.ts [hunk 1]
```diff
@@ -1,3 +1,5 @@
+import { syncBalance } from '@core/account/actions/syncBalance'
+import { selectedAccountId } from '@core/account/stores/selected-account-id.store'
 import { selectedAccount } from '@core/account/stores/selected-account.store'
```
Comment (maxwellmattryan) [inline packages/shared/lib/core/wallet/actions/claimActivity.ts:3]: These should be able to be imported with in one statement; check to make sure the barrel files are exporting them.

File: packages/shared/lib/core/wallet/stores/assets.store.ts [hunk 2]
```diff
@@ -1,6 +1,6 @@
 import { BASE_TOKEN } from '@core/network'
-import { activeProfile } from '@core/profile'
-import { selectedAccount } from '@core/account'
+import { activeProfile } from '@core/profile/stores/active-profile.store'
+import { selectedAccount } from '@core/account/stores/selected-account.store'
```
Comment (maxwellmattryan) [inline packages/shared/lib/core/wallet/stores/assets.store.ts:3]: Same as above

File: packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts [hunk 3]
```diff
@@ -1,4 +1,4 @@
-import { selectedAccount } from '@core/account'
+import { selectedAccount } from '@core/account/stores/selected-account.store'
```
Comment (maxwellmattryan) [inline packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts:1]: Same as above

**Review by maxwellmattryan — CHANGES_REQUESTED** [review]
Requested some minor changes

**Review by maxwellmattryan — APPROVED** [review]
