### PR TITLE
fix: reactivity issue after user gets enough mana to cover the block cost

### LINKED ISSUE #8505: [Task]: Fix reactivity issue after user gets enough mana to cover the block cost
### Task description

There has been a bug reported in the delegation tab, though it might be a bug present in all block confirmation screens 
> Hello! Just wanted to report a small issue with delegation. As you can see in the video, the user is not able to delegate immediately after waiting to get enough Mana. One keeps getting the "waiting message". However, Mana is already in the account and it works well after simply switching tabs.

On the same popup, the time runs and the user has enough mana, but the button is still disabled. Reopening seems to fix
image
image

### PR DESCRIPTION
**Pull request by cpl121**
Closes #8505 

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Changelog

```
- Please write a list of changes
```

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/desktop/components/ManaBox.svelte [hunk 1]
```diff
@@ -57,6 +58,9 @@
                     secondsRemainingCountdownInterval = setInterval(() => {
                         secondsRemaining -= 1
                         if (secondsRemaining <= 0) {
+                            refreshTransactionInfo().then(() => {
```
Comment (begonaalvarezd) [inline packages/desktop/components/ManaBox.svelte:61]: would be good fixing these linter warnings 🙏🏼

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by begonaalvarezd — APPROVED** [review]
