### PR TITLE
fix: avoid text overflowing from toasts

### LINKED ISSUE #7207: [Task]: Fix text overflow in notifications
### Task description

image_480

### Requirements

Long texts should not overflow the notification

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by VmMad**
## Summary

> Fixes #7207 

...

## Changelog

```
- Fixed also the toasts not being clickable
```

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by marc2332 — APPROVED** [review]

File: packages/shared/components/Alert.svelte [hunk 1]
```diff
@@ -55,9 +55,12 @@
         icon={TOAST_STYLE[type].icon}
         classes="fill-current {TOAST_STYLE[type].iconColor}"
     />
-    <div class="flex flex-auto flex-col px-4">
-        <Text fontWeight={FontWeight.semibold} class="flex text-13 {TOAST_STYLE[type].messageColor}">{message}</Text>
-    </div>
+    <message-container class="w-full flex flex-auto flex-col px-4">
+        <Text
+            fontWeight={FontWeight.semibold}
+            class="flex text-13 text-ellipsis overflow-hidden {TOAST_STYLE[type].messageColor}">{message}</Text
```
Comment (begonaalvarezd) [inline packages/shared/components/Alert.svelte:61]: Not sure this text-ellipsis and overflow-hidden are working. I am testing creating a notification with a very large text and its being cut. I would not add that at all because we actually should never cut a message, and instead add a `break-words` class so the message is always displayed

Comment (begonaalvarezd) [reply packages/shared/components/Alert.svelte:61]: The same should be added not only to alerts but to any type of app notification message

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

File: packages/shared/components/Toast.svelte [hunk 2]
```diff
@@ -59,8 +59,8 @@
                 <Icon icon={style?.icon} />
             {/if}
         </div>
-        <div class="flex flex-auto flex-col px-4">
-            <span class="flex text-12 text-{style?.messageColor}">{toast.message}</span>
+        <div class="w-full flex flex-auto flex-col px-4 pr-8">
+            <span class="flex text-12 text-{style?.messageColor} break-all">{toast.message}</span>
```
Comment (begonaalvarezd) [inline packages/shared/components/Toast.svelte:63]: same here, `break-words`

File: packages/shared/components/Toast.svelte [hunk 3]
```diff
@@ -59,8 +59,8 @@
                 <Icon icon={style?.icon} />
             {/if}
         </div>
-        <div class="flex flex-auto flex-col px-4">
-            <span class="flex text-12 text-{style?.messageColor}">{toast.message}</span>
+        <div class="w-full flex flex-auto flex-col px-4 pr-8">
```
Comment (begonaalvarezd) [inline packages/shared/components/Toast.svelte:62]: Do we need this `pr-8`?

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by begonaalvarezd — APPROVED** [review]
