### PR TITLE
fix: NetworkSummaryModal

### LINKED ISSUE #4767: [Task]: Fix NetworkSummaryModal with broken layout
### Task description
The NetworkSummaryModal component is with a broken layout so we need to make it more resilient and not break it when info is missing

Image

### Requirements
- [x] Layout does not break with missing info

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by jeeanribeiro**
## Summary
Refactors code to improve the resiliency of layout and maintainability

## Changelog
```
- Refactors NetworkSummaryModal
- Refactors NETWORK_HEALTH_COLORS and NETWORK_STATUS_DESCRIPTION constants
```

## Relevant Issues
closes #4767 

### Platforms
- __Desktop__
  - [ ] MacOS
  - [x] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

## Checklist
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/components/modals/NetworkSummaryModal.svelte [hunk 1]
```diff
@@ -3,43 +3,51 @@
...
     <network-indicator-content class="flex flex-col">
-        {#if $activeProfile?.isDeveloperProfile}
-            <Text type="h3" classes="px-7 pt-5">{$nodeInfo?.protocol?.networkName}</Text>
-        {/if}
-        <div class="px-7 pb-5 text-13 text-{NETWORK_HEALTH_COLORS[health]}-500">
-            {localize(`views.dashboard.network.${description}`)}
+        <div class="py-5">
+            {#if $activeProfile?.isDeveloperProfile}
+                <Text type={TextType.h3} classes="px-7">{$nodeInfo?.protocol?.networkName}</Text>
+            {/if}
```
Comment (MarkNerdi) [inline packages/shared/components/modals/NetworkSummaryModal.svelte:32]:
```suggestion
            {#if $activeProfile?.isDeveloperProfile && $nodeInfo?.protocol?.networkName}
                <Text type={TextType.h3} classes="px-7">{$nodeInfo?.protocol?.networkName}</Text>
            {/if}
```

if any of `nodeinfo.protocol.networkname` can be undefined, add it to the if condition, else an empty Text element will be rendered. 

If it cannot be undefined, remove the `?`

**Review by MarkNerdi — COMMENTED** [review]
Nice refactoring and restructuring!
1 small comment, then good to go

**Review by MarkNerdi — APPROVED** [review]
