### PR TITLE
fix: unit selection shows undefined

### LINKED ISSUE #3982: [Subtask] UnitSelection on SendForm shows undefined for native tokens

### PR DESCRIPTION
**Pull request by MarkNerdi**
## Summary
If the asset does not contain a subunit, which is the case for all native tokens, then we don't display a dropdown.

## Changelog

```
- show dropdown only if we have multiple options for the unit
- show unit as text if we have no option
```

## Relevant Issues
Closes #3982 

...

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/components/inputs/UnitInput.svelte [hunk 1]
```diff
@@ -37,4 +38,24 @@
...
+    <div class="block relative small">
+        <div
+            class="selection relative flex flex-row space-x-0 pl-1 pb-1.5 items-end w-full whitespace-nowrap bg-white dark:bg-gray-800 pr-0 border-transparent"
+        >
+            <Text fontSize="16" fontWeight="semibold" classes="text-gray-800 dark:text-white" smaller>
+                {unit}
+            </Text>
+        </div>
+    </div>
+{/if}
```
Comment (nicole-obrien) [inline packages/shared/components/inputs/UnitInput.svelte:53]: Can we add this logic to the dropdown component itself, so if there is only one item it will only show the text

**Review by nicole-obrien — CHANGES_REQUESTED** [review]
Lets move the single item display logic to the dropdown component itself.

**Review by nicole-obrien — APPROVED** [review]
🏁
