### PR TITLE
fix: unlock stronghold at the end of the onboarding process

### LINKED ISSUE #4823: [Task]: Impossible to restore Stronghold if it gets locked.
### Task description

During the restore with stronghold flow, the stronghold password has to be inputted. If we wait long enough, the stronghold gets locked again and it becomes impossible to create a new profile. There is no usable error message or pop-up shown to the user

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by cpl121**
Closes #4823 

## Summary

Unlock stronghold at the end of the onboarding process to avoid an error due to the stronghold file being locked for a long time

## Changelog

```
- If the restore type is `stronghold`, unlock the stronghold file setting password at the end of the onboarding process
```

### Platforms

-   **Desktop**
    -   [ ] MacOS
    -   [X] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

- Create a profile and save a stronghold backup
- Create a new profile
- Testnet network
- Restore an existing Tesnet profile
- Use Stronghold backup
- Select the stronghold file and set the password
- Wait 2 minutes at the next 3 views
- Finish the restore process without errors

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [X] I have followed the contribution guidelines for this project
-   [X] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [x] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/desktop/views/onboarding/views/complete-onboarding/views/EnterNameView.svelte [hunk 1]
```diff
@@ -16,6 +18,17 @@
...
+                const MILLISECONDS_TO_EXPIRE_STRONGHOLD_PASSWORD =
+                    DEFAULT_STRONGHOLD_PASSWORD_TIMEOUT_IN_MINUTES * SECONDS_PER_MINUTE * MILLISECONDS_PER_SECOND
+                const isStrongholdPasswordExpired =
+                    new Date().getTime() - $onboardingProfile?.timeStrongholdLastUnlocked?.getTime() >
+                    MILLISECONDS_TO_EXPIRE_STRONGHOLD_PASSWORD
+                if (isStrongholdPasswordExpired) {
+                    handleError({ message: localize('views.settings.strongholdPasswordTimeout.description') })
+                    throw new Error()
+                }
+            }
```
Comment (begonaalvarezd) [inline packages/desktop/views/onboarding/views/complete-onboarding/views/EnterNameView.svelte:31]: We should try avoiding code duplication, this is repeated

Comment (begonaalvarezd) [reply packages/desktop/views/onboarding/views/complete-onboarding/views/EnterNameView.svelte:31]: Also, we should not manage any of this logic here, we dont even know what is the timeout the bindings are using

Comment (begonaalvarezd) [reply packages/desktop/views/onboarding/views/complete-onboarding/views/EnterNameView.svelte:31]: I would first check what is the error (if there is any), and from there work
- use the error
- if there is no error but there is still a crash preventing the user from proceeding, we could use `isStrongholdUnlocked`

File: packages/desktop/views/onboarding/views/complete-onboarding/views/EnterPinView.svelte [hunk 2]
```diff
@@ -29,6 +31,17 @@
     }
 
     async function handleSetPin(): Promise<void> {
+        if ($onboardingProfile.restoreProfileType === RestoreProfileType.Stronghold) {
```
Comment (begonaalvarezd) [inline packages/desktop/views/onboarding/views/complete-onboarding/views/EnterPinView.svelte:34]: all this is repeated, we should try to avoid code duplication

File: packages/desktop/views/onboarding/views/restore-from-stronghold/views/UnlockStrongholdView.svelte [hunk 3]
```diff
@@ -20,7 +20,7 @@
             busy = true
             try {
                 await restoreBackupFromStrongholdFile(strongholdPassword)
-                updateOnboardingProfile({ strongholdPassword })
+                updateOnboardingProfile({ strongholdPassword, timeStrongholdLastUnlocked: new Date() })
```
Comment (begonaalvarezd) [inline packages/desktop/views/onboarding/views/restore-from-stronghold/views/UnlockStrongholdView.svelte:23]: we could remove this extra key

File: packages/shared/lib/contexts/onboarding/interfaces/onboarding-profile.interface.ts [hunk 4]
```diff
@@ -12,6 +12,7 @@ export interface IOnboardingProfile extends IPersistedProfile {
     // Stronghold setup data
     importFile?: ImportFile
     importFilePath?: string
+    timeStrongholdLastUnlocked?: Date
```
Comment (begonaalvarezd) [inline packages/shared/lib/contexts/onboarding/interfaces/onboarding-profile.interface.ts:15]: we shouldnt need this

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
Added some comments 🙏🏼

File: packages/desktop/views/onboarding/views/complete-onboarding/CompleteOnboardingRouterView.svelte [hunk 5]
```diff
@@ -7,10 +7,22 @@
...
+    $: verifyAndRestoreStronghold(), $completeOnboardingRoute
+
+    async function verifyAndRestoreStronghold() {
+        if ($onboardingProfile?.restoreProfileType === RestoreProfileType.Stronghold) {
+            const _isStrongholdUnlocked = await isStrongholdUnlocked()
+            if (!_isStrongholdUnlocked) {
+                await restoreBackupFromStrongholdFile($onboardingProfile.strongholdPassword)
+            }
+        }
+    }
```
Comment (begonaalvarezd) [inline packages/desktop/views/onboarding/views/complete-onboarding/CompleteOnboardingRouterView.svelte:25]: `restoreBackupFromStrongholdFile` is quite intense, i think we could just update the password, wydt?
`import { setStrongholdPassword } from '@core/profile-manager'`
```suggestion
    // Note: needed to cover the cases where the user has waited so long that the stronghold is locked
    $: $completeOnboardingRoute, unlockStronghold()
    function unlockStronghold(): void {
        if ($onboardingProfile?.restoreProfileType === RestoreProfileType.Stronghold) {
            void setStrongholdPassword($onboardingProfile.strongholdPassword)
        }
    }
```

Comment (begonaalvarezd) [reply packages/desktop/views/onboarding/views/complete-onboarding/CompleteOnboardingRouterView.svelte:25]: Also, I was thiking we dont need this logic in all these routes, its only important in the final view, right before doing all the logic
image

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
Great work, added some comments 🙏🏼

File: packages/desktop/views/onboarding/views/complete-onboarding/views/FinishOnboardingView.svelte [hunk 6]
```diff
@@ -1,12 +1,27 @@
...
+        onboardingProfile,
+    } from '@contexts/onboarding'
     import { mobile } from '@core/app'
     import { localize } from '@core/i18n'
     import { checkOrConnectLedger } from '@core/ledger'
+    import { isStrongholdUnlocked, setStrongholdPassword } from '@core/profile-manager'
     import { Animation, Button, Icon, Text, TextHint } from '@ui'
     import { onboardingRouter } from '@views/onboarding/onboarding-router'
 
+    async function verifyAndRestoreStronghold(): Promise<void> {
```
Comment (begonaalvarezd) [inline packages/desktop/views/onboarding/views/complete-onboarding/views/FinishOnboardingView.svelte:16]: I would say this name does not represent anymore what it means

Comment (begonaalvarezd) [inline packages/desktop/views/onboarding/views/complete-onboarding/views/FinishOnboardingView.svelte:16]: I would say this name does not represent anymore what the function does

File: packages/desktop/views/onboarding/views/complete-onboarding/views/FinishOnboardingView.svelte [hunk 7]
```diff
@@ -1,12 +1,27 @@
...
+        if ($onboardingProfile?.restoreProfileType === RestoreProfileType.Stronghold) {
+            const _isStrongholdUnlocked = await isStrongholdUnlocked()
```
Comment (begonaalvarezd) [inline packages/desktop/views/onboarding/views/complete-onboarding/views/FinishOnboardingView.svelte:18]: to simplify and also prevent possible race conditions, i think we are safe by always unlocking, without checking

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
almost there, added minor comments 🙏🏼

**Comment by begonaalvarezd** [comment]
@cpl121 lets also update the PR title and description 🙏🏼

**Review by begonaalvarezd — APPROVED** [review]
🔥
