### PR TITLE
fix: adds truncate to profile name [develop]

### LINKED ISSUE #1721: [UI] Profile names may obscure other profile names
### Issue description

If the profile name is too long it may obscure other profile names in the profile overview/login window.

Bildschirmfoto 2021-12-13 um 16 01 54

### Firefly version

1.3.0

### OS details

macOS 12.0.1

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Create a new profile with close to 20 characters 
2. Log out
3. Enjoy

### Expected behaviour

The profile overview/login window should possibly only show the first x characters of the profile name, followed by three dots "...".

### Actual behaviour

The profile overview/login window shows the whole profile name and obscures ui to its left and right.

### Errors

_No response_

### PR DESCRIPTION
**Pull request by jeeanribeiro**
## Summary
Adds truncate and fixed width for profile name because if the name is too big it will obscure others in the Profile selection screen

## Relevant Issues
closes #1721

## Type of Change
- [x] __Fix__ - a change that fixes an issue

### Platforms
Please select any platforms where your changes have been tested.
- __Desktop__
	- [ ] MacOS
	- [x] Linux
	- [ ] Windows
- __Mobile__
	- [ ] iOS
	- [ ] Android

## Checklist
Please tick all of the following boxes that are relevant to your changes, and delete those that are not.
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have verified that my latest changes pass CI workflows for testing and linting

### CODE REVIEW

File: packages/shared/components/Profile.svelte [hunk 1]
```diff
@@ -44,7 +44,7 @@
                 <Text type="h3" classes="text-white">{getInitials()}</Text>
             {/if}
         </div>
-        <div class="flex flex-row items-baseline space-x-1.5">
+        <div class="flex flex-row items-baseline space-x-1.5 w-full">
```
Comment (MarkNerdi) [inline packages/shared/components/Profile.svelte:47]: with this, short names are not centered anymore. Try `content-center`

**Review by MarkNerdi — APPROVED** [review]
