### PR TITLE
fix: freezing long password [stardust-develop]

### LINKED ISSUE #1172: Software freezes while setting up an extra secure password
## Issue description

While setting up my wallet iI decided ti choose an very extra secure password of about 256 characters, managed by a Passwordmanager, the Software instantly freezes and don't respond anymore.

## Wallet version

Firefly v. 1.1.0 - officiall download

## System specification

Win10 64bit

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Open a new wallet copy past a password with 256 characters like this: 
qt\V;;W-hÄP".^bWeWjs`}Uds"^.9eGUa;{lV|E?u3ü)l-7~cmzZ4SfggQsYzi.1^hWZVU!NsLICj0X*`%>epd\ÜmcZPS!eB~LQ P>NKIDh71?Zvb_<Cbgs%yöyoyX4Q8taü${8|'Xf+HJ9{V0"3kREfSAOßÜ@_&1ku3Gßö8;9LPlPIo{BPB<5N 5|(9cHJx3?k.c}%*q7~Z2PKÄö(BAb/t%gv%bFfJ!6zü7e8ä9apqV'574v@''ü}{W_eCN%O7e

## Expected behaviour

dont freeze ;D

## Actual behaviour

freeze 

## Errors

no error log at all

### PR DESCRIPTION
**Pull request by jeeanribeiro**
## Summary
When long passwords are used to create a new profile, the app freezes because of the zxcvbn password strength algorithm, and I've limited the number of characters being used in this function as [recommended in lib's repo readme](https://github.com/dropbox/zxcvbn#user-content-performance)

### Changelog
```
- adds wrapper function to check password strength
```

## Relevant Issues
closes #1172

## Type of Change
- [x] __Fix__ - a change which fixes an issue

### Platforms
Please select any platforms where your changes have been tested.
- __Desktop__
	- [ ] MacOS
	- [x] Linux
	- [ ] Windows
- __Mobile__
	- [ ] iOS
	- [ ] Android

### Instructions
Create a new profile, copy and paste a password with 256 characters like this:
```
qt\V;;W-hÄP".^bWeWjs}Uds"^.9eGUa;{lV|E?u3ü)l-7~cmzZ4SfggQsYzi.1^hWZVU!NsLICj0X*%>epd\ÜmcZPS!eBLQ P>NKIDh71?Zvb_<Cbgs%yöyoyX4Q8taü${8|'Xf+HJ9{V0"3kREfSAOßÜ@_&1ku3Gßö8;9LPlPIo{BPB<5N 5|(9cHJx3?k.c}%*q7Z2PKÄö(BAb/t%gv%bFfJ!6zü7e8ä9apqV'574v@''ü}{W_eCN%O7e
```

## Checklist
Please tick all of the following boxes that are relevant to your changes, and delete those that are not.
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have verified that my latest changes pass CI workflows for testing and linting

### CODE REVIEW

File: packages/shared/routes/setup/Password.svelte [hunk 1]
```diff
@@ -66,6 +67,16 @@
...
     }
+
+    function checkPasswordStrength(password: string): any {
+        const NUMBER_OF_STRENGTH_VALIDATION_CHARS = 64
+        const limitedPassword = password.substring(0, NUMBER_OF_STRENGTH_VALIDATION_CHARS - 1)
+        const hasCheckedPasswordChanged = lastCheckedPassword !== limitedPassword
+        if (hasCheckedPasswordChanged) {
+            lastCheckedPassword = limitedPassword
+            return zxcvbn(limitedPassword)
+        }
```
Comment (MarkNerdi) [inline packages/shared/routes/setup/Password.svelte:78]: If it returns undefined, it finds no translation with key GENERAL.PASSWORDSTRENGTHUNDEFINED

**Review by MarkNerdi — APPROVED** [review]
