### PR TITLE
fix: error when a transaction is rejected with ledger

### LINKED ISSUE #7530: [Task]: fix error when a transaction is rejected with ledger
### Task description

fix error when a transaction is rejected with ledger

### Requirements

fix error when a transaction is rejected with ledger

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by cpl121**
Closes #7530 

## Summary

> fix error when a transaction is rejected with ledger

## Changelog

```
- fix error when a transaction is rejected with ledger
```

### Platforms

-   **Desktop**
    -   [ ] MacOS
    -   [X] Linux
    -   [ ] Windows

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [X] I have followed the contribution guidelines for this project
-   [X] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [x] I have verified that my latest changes pass CI workflows for testing and linting
-   [x] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/desktop/components/popups/send/SendConfirmationPopup.svelte [hunk 1]
```diff
@@ -178,8 +178,13 @@
...
 
     async function sendOutputAndClosePopup(): Promise<void> {
-        await sendOutput(preparedOutput)
-        closePopup()
+        try {
+            await sendOutput(preparedOutput)
+        } catch (err) {
+            handleError(err)
+        } finally {
+            closePopup()
```
Comment (begonaalvarezd) [inline packages/desktop/components/popups/send/SendConfirmationPopup.svelte:186]: If there was an error we should probably not close the popup, if before this gave an exception the popup was kept open, i would probably keep the same logic, or did you change it for a reason?

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

File: packages/desktop/components/popups/send/SendConfirmationPopup.svelte (hunk 1 above)
Comment (cpl121) [reply packages/desktop/components/popups/send/SendConfirmationPopup.svelte:186]: When I reject a transaction from the ledger I receive an error, also this popup cannot be closed. If I dont close the popup after the error, the user will have the screen locked and unable to do anything in the ledger 🥲 
Whether you accept or reject the transaction from the ledger, I think it is good to close the popup

**Review by begonaalvarezd — APPROVED** [review]
