### PR TITLE
feat: fix available balance toggle on tesnet and custom network

### LINKED ISSUE #8500: [Task]: Fix available balance toggle on tesnet and custom network
Available balance is not shown after clicking on it

### PR DESCRIPTION
**Pull request by evavirseda**
## Summary

> Closes #8500 

...

## Changelog

```
- Please write a list of changes
```

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/components/labels/TogglableAssetBalanceLabel.svelte [hunk 1]
```diff
@@ -22,16 +23,21 @@
...
             <Text type={TextType.p} fontWeight={FontWeight.medium} color="gray-600" darkColor="gray-500">
                 {localize('general.availableBalanceWithValue', {
                     values: {
-                        balance: isToggled
-                            ? formatCurrency(availableMarketValue)
-                            : formatTokenAmountBestMatch(asset?.balance?.available, asset?.metadata),
+                        balance:
+                            isToggled &&
+                            $activeProfile?.network?.id !== NetworkId.Testnet &&
+                            $activeProfile?.network?.id !== NetworkId.Custom
```
Comment (marc2332) [inline packages/shared/components/labels/TogglableAssetBalanceLabel.svelte:38]: can you move this to a reactive variable so you don't duplicate it

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by cpl121 — APPROVED** [review]
LGTM

**Review by marc2332 — APPROVED** [review]
