### PR TITLE
fix: confirm button in create delegation popup

### LINKED ISSUE #8431: [Task]: Display `Generated Mana` message when insufficient mana on create delegation
when we try to delegate without enough mana, they see a disabled `Confirm` button but get no info on when we'll have enough mana... We need to make it clearer by showing a message about mana generation progress

Image

### PR DESCRIPTION
**Pull request by cpl121**
Closes #8431 

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Changelog

```
- Please write a list of changes
```

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/desktop/components/popups/CreateDelegationPopup.svelte [hunk 1]
```diff
@@ -50,12 +50,7 @@
         !addressError &&
         transactionInfo.preparedTransaction &&
         !transactionInfo.preparedTransactionError
-    $: displayManaBox =
-        !!accountAddress &&
-        !addressError &&
-        validAmount &&
-        transactionInfo.preparedTransaction &&
-        !transactionInfo.preparedTransactionError
+    $: displayManaBox = !!accountAddress && !addressError && validAmount
```
Comment (marc2332) [inline packages/desktop/components/popups/CreateDelegationPopup.svelte:53]: How is displaying the `ManaBox` or not, related to the confirm button? Shouldn't you be tweaking `confirmAllowed` ?

**Review by evavirseda — CHANGES_REQUESTED** [review]
is not working, when you open the popup, it shows you the message `Generating mana...x minutes` but if you reopen it, the message doesn't appear even though you still don't have enough mana... :pray:

**Review by evavirseda — APPROVED** [review]
nice job :rocket:

**Review by marc2332 — APPROVED** [review]
