### PR TITLE
fix: available balance reactivity in `SendFormPopup`

### LINKED ISSUE #7427: [Task]: Fix available balance reactivity in SendFormPopup
### Task description

If user initiates new send flow and opens SendFormPopup while there is a pending transaction in progress, when that transaction gets confirmed the available balance is not updated in the popup. User can than input the value that is greater than the new available balance, because the old available balance is still displayed and used in validation, and proceed to SendConfirmationPopup where an error notification will be thrown.

Make available balance reactive in `SendFormPopup` so it reflects the correct state of the balance.
image

### Requirements

in `SendFormPopup`
- [ ] display correct value of available balance
- [ ] user cannot input and pass validation with incorrect amount 

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by evavirseda**
## Summary

> Closes #7427 

...

## Changelog

```
- make availableBalance reactive
```

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by brancoder — APPROVED** [review]
LGTM :+1:

File: packages/shared/components/inputs/AssetAmountInput.svelte [hunk 1]
```diff
@@ -40,6 +40,7 @@
     $: marketAmount = getMarketAmountFromAssetValue(bigAmount, asset)
     $: max = parseCurrency(formatTokenAmountDefault(availableBalance, asset?.metadata, unit, false))
     $: rawAmount = bigAmount?.toString()
+    $: asset = $visibleSelectedAccountAssets?.[$activeProfile?.network?.id]?.baseCoin ?? asset
```
Comment (begonaalvarezd) [inline packages/shared/components/inputs/AssetAmountInput.svelte:43]: I havent tested the code but from reading the changes I think this can lead to issues if for some reason the `visibleSelectedAccountAssets` changes, `asset` is binded in `<AssetDropdown bind:asset readonly={disableAssetSelection} />` and this code looks like its going to override it

Comment (begonaalvarezd) [reply packages/shared/components/inputs/AssetAmountInput.svelte:43]: Indeed, this code doesnt work, you cant even select a native token

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by begonaalvarezd — APPROVED** [review]
