### PR TITLE
fix: crash idle logout & mobile initialization

### LINKED ISSUE #3657: [Task]: Fix auto-lock at `Idle`
### Description

Currently the automatic lock feature is not working as espected, we have to touch the screen then lock is enabled.
At the `Idle` component there is only touch event interaction for mobile, we need to find a solution.
To reproduce the issue, we need to login and await the necessary minutes for auto-lock without touching the screen. Finally touch the screen.

### Requirements

- [ ] Works on Android
- [ ] Works on iOS

### PR DESCRIPTION
**Pull request by begonaalvarezd**
## Summary

> Please summarize your changes, describing __what__ they are and __why__ they were made.

This PR aims to fix 2 issues:
- If you had the receive QR drawer open when the idle timeout was triggered, the app crashed because the `Wallet.svelte` component wasnt destroyed at a right time because of the child transitions. Adding `|local` to the transitions fixes the issue and allows the component to destroy on time without the need to wait for the transitions. [Source](https://svelte.dev/docs#template-syntax-element-directives-transition-fn-transition-events): `Local transitions only play when the block they belong to is created or destroyed, not when parent blocks are created or destroyed.`
- On mobile, for the idle timeout to start, the user had to do some explicit interaction to the screen, which in mobile is a touch event. This PR fixes the issue by updating the timeout when the accounts are loaded. 

## Changelog

```
- fix: idle logout crash due to transitioned component not being destroyed
- fix: idle timeout not starting until the user touches the screen
```

## Relevant Issues

> Please list any related issues using [development keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

Close #3657

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [x] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/routes/dashboard/wallet/Wallet.svelte [hunk 1]
```diff
@@ -482,15 +482,15 @@
                 >
                     <DashboardPane classes="w-full">
                         {#if $walletRoute === WalletRoute.Assets}
-                            <div class="h-full" in:fade={{ duration: 200 }} out:fade={{ duration: 200 }}>
+                            <div class="h-full" in:fade|local={{ duration: 200 }} out:fade|local={{ duration: 200 }}>
```
Comment (paul-boegelsack) [inline packages/shared/routes/dashboard/wallet/Wallet.svelte:485]: Didn't know this local option, thanks for the explanation 👍

**Review by paul-boegelsack — APPROVED** [review]
🚀
