### PR TITLE
fix: error handling on wrong stronghold password in claiming flow

### LINKED ISSUE #4673: [Task]: Fix Stronghold Shimmer claiming flow on wrong password
### Task description

If the user enters a wrong password, Firefly throws two errors instead of one.

### Requirements

- [x] Ensure only one error is thrown
- [x] Ensure flow is recoverable after error (spinner spins forever) - if password is wrong stop continuing

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by kraftjs**
## Summary

> Please summarize your changes, describing __what__ they are and __why__ they were made.

Firefly freezes on error handling when inputting incorrect password in the Stronghold onboarding claim flow.

## Changelog

```
- Moved busy = false statement into a finally block
- Check for incorrect password error before throwing UnableToRestoreBackupForProfileManagerError
```

## Relevant Issues

> Please list any related issues using [development keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

Closes #4673 

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [x] MacOS
  - [ ] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/lib/contexts/onboarding/helpers/restoreBackupForProfileManager.ts [hunk 1]
```diff
@@ -20,6 +20,11 @@ export async function restoreBackupForShimmerClaimingProfileManagerHelper(
         await get(manager)?.setClientOptions(clientOptions)
     } catch (err) {
         console.error(err)
-        throw new UnableToRestoreBackupForProfileManagerError()
+        // Check if thrown err is because of an invalid password
+        if (err?.error.match(/`invalid stronghold password`/)) {
```
Comment (maxwellmattryan) [inline packages/shared/lib/contexts/onboarding/helpers/restoreBackupForProfileManager.ts:24]: We should put this into a `const` object for Stronghold-based errors or something, so we can use it elsewhere

**Review by maxwellmattryan — CHANGES_REQUESTED** [review]

File: packages/shared/lib/contexts/onboarding/helpers/restoreBackupForProfileManager.ts (hunk 1 above)
Comment (kraftjs) [reply packages/shared/lib/contexts/onboarding/helpers/restoreBackupForProfileManager.ts]: Already exists a ClientError object. Went ahead an added the `invalid stronghold password` error to it

**Review by cvarley100 — APPROVED** [review]
