### PR TITLE
fix: dont store stronghold version on ledger profiles

### LINKED ISSUE #7291: [Task]: fix dont store stronghold version on ledger profiles
### Task description

Currently the stronghold version is being stored in the profiles with ledger, and stronghold is only used for software profiles

### Requirements

- Set the stronghold version only for software profiles
- Ledger profiles that have stronghold version, migrate to remove it

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by cpl121**
Closes #7291 

## Summary

> dont store stronghold version on ledger profiles

## Changelog

```
- Remove strongholdVersion in Ledger profiles
- Dont store stronghold version when creating ledger profiles
```

### Platforms

-   **Desktop**
    -   [ ] MacOS
    -   [X] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

- Check in the `localStorage` that the `strongholdVersion` of the Ledger profiles no longer appears
- Create a new ledger profile and check that `strongholdVersion` is not stored

## Checklist

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [x] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/desktop/views/onboarding/views/create-profile/views/ChooseCreateProfileFlowView.svelte [hunk 1]
```diff
@@ -27,8 +27,10 @@
 
     async function onProfileTypeClick(createProfileType: CreateProfileType): Promise<void> {
         isBusy = { ...isBusy, [createProfileType]: true }
-        const type = createProfileType === CreateProfileType.Ledger ? ProfileType.Ledger : ProfileType.Software
-        updateOnboardingProfile({ createProfileType, type })
+        const isLedgerProfile = createProfileType === CreateProfileType.Ledger
```
Comment (begonaalvarezd) [inline packages/desktop/views/onboarding/views/create-profile/views/ChooseCreateProfileFlowView.svelte:30]: ideally, you should also update `buildInitialOnboardingProfile` in `packages/shared/lib/contexts/onboarding/helpers/buildInitialOnboardingProfile.ts` so it doesnt initialize the stronghold version from the very begining

File: packages/shared/lib/core/profile/interfaces/persisted-profile.interface.ts [hunk 2]
```diff
@@ -20,6 +20,6 @@ export interface IPersistedProfile {
     lastUsedAccountIndex?: number
     clientOptions: IClientOptions
     forceAssetRefresh: boolean
-    strongholdVersion: StrongholdVersion
+    strongholdVersion?: StrongholdVersion
```
Comment (begonaalvarezd) [inline packages/shared/lib/core/profile/interfaces/persisted-profile.interface.ts:23]: if you make this optional, ideally you should also update `packages/shared/lib/core/profile/actions/active-profile/saveActiveProfile.ts`

File: packages/desktop/views/onboarding/views/create-profile/views/ChooseCreateProfileFlowView.svelte [hunk 3]
```diff
@@ -27,8 +27,10 @@
...
+        const type = isLedgerProfile ? ProfileType.Ledger : ProfileType.Software
+        const strongholdVersion = isLedgerProfile ? undefined : $onboardingProfile.strongholdVersion
```
Comment (begonaalvarezd) [inline packages/desktop/views/onboarding/views/create-profile/views/ChooseCreateProfileFlowView.svelte:32]: I would improve this logic here, becasue you are either taking the value that already exists, or undefining it, and use it to update the value that already exists. There shouldnt be a stronghold version in the onboarding profile at a this point, so you should set it here, eg
```ts
        const isLedgerProfile = createProfileType === CreateProfileType.Ledger
        const type = isLedgerProfile ? ProfileType.Ledger : ProfileType.Software
        const strongholdVersion = isLedgerProfile ? undefined : STRONGHOLD_VERSION
        updateOnboardingProfile({ createProfileType, type, ...(strongholdVersion && { strongholdVersion }) })
```

File: packages/shared/lib/core/profile/actions/profiles/checkAndMigrateProfiles.ts [hunk 4]
```diff
@@ -289,3 +291,11 @@ function persistedProfileMigrationToV13(
 
     saveProfile(newProfile as IPersistedProfile)
 }
+
+function persistedProfileMigrationToV14(existingProfile: IPersistedProfile): void {
+    const isLedgerProfile = existingProfile?.type === ProfileType.Ledger
+    if (isLedgerProfile) {
+        existingProfile.strongholdVersion = undefined
```
Comment (begonaalvarezd) [inline packages/shared/lib/core/profile/actions/profiles/checkAndMigrateProfiles.ts:298]: maybe you can try a delete so the key also gets removed?
```suggestion
        delete existingProfile.strongholdVersion
```

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by begonaalvarezd — APPROVED** [review]
🔥
