### PR TITLE
fix: allow restoration on Shimmer network with old Stronghold backups

### LINKED ISSUE #4763: [Task]: Allow restoration on shimmer network with old strongholds
### Task description

Currently we are blocking restoration of stronghold if its an older stronghold or from a different network. We should allow the user to import the stronghold anyway and use it to import the seed and then just recover accounts.

### Requirements

- [x] Allow older / mismatched strongholds
- [x] Call recoverAccounts in all restore flows during loading

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by maxwellmattryan**
## Summary

> Please summarize your changes, describing __what__ they are and __why__ they were made.

...

## Changelog

```
- Adds fallback to restore by copy if first try fails
```

## Relevant Issues

> Please list any related issues using [development keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

Closes #4763 

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [x] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

Test with both old and new Stronghold backups in the normal profile recovery onboarding flow.

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [x] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/lib/contexts/onboarding/actions/restoreBackupFromStrongholdFile.ts [hunk 1]
```diff
@@ -1,19 +1,34 @@
...
-     */
-    await validateStrongholdCoinType(get(profileManager), networkProtocol)
+        /**
+         * NOTE: We must check that the Stronghold file's coin_type matches the current networkProtocol
+         * and is not based on an alternate protocol.
+         */
+        await validateStrongholdCoinType(get(profileManager), networkProtocol)
 
-    updateOnboardingProfile({ lastStrongholdBackupTime: new Date() })
+        updateOnboardingProfile({ lastStrongholdBackupTime: new Date() })
```
Comment (Tuditi) [inline packages/shared/lib/contexts/onboarding/actions/restoreBackupFromStrongholdFile.ts:32]: Shouldn't this be outside the else statement?

File: packages/shared/routes/onboarding/views/profile-recovery/views/BackupPasswordView.svelte [hunk 2]
```diff
@@ -31,7 +31,11 @@
                 if ($onboardingProfile?.setupType === ProfileSetupType.Claimed) {
                     await restoreBackupForShimmerClaimingProfileManager(strongholdPassword)
                 } else {
-                    await restoreBackupFromStrongholdFile(strongholdPassword)
+                    try {
+                        await restoreBackupFromStrongholdFile(strongholdPassword)
+                    } catch {
+                        await restoreBackupFromStrongholdFile(strongholdPassword, true)
+                    }
```
Comment (Tuditi) [inline packages/shared/routes/onboarding/views/profile-recovery/views/BackupPasswordView.svelte:38]: Why not move this try/catch statement into `restoreBackupFromStrongholdFile`? You could rid yourself from an argument that is sometimes there, sometimes not and which is already initialized.

**Review by Tuditi — CHANGES_REQUESTED** [review]
Still have to test it out, but I'll wait for the changes.

File: packages/shared/lib/contexts/onboarding/actions/restoreBackupFromStrongholdFile.ts (hunk 1 above)
Comment (maxwellmattryan) [reply packages/shared/lib/contexts/onboarding/actions/restoreBackupFromStrongholdFile.ts:32]: It's tricky because only the `else` branch code actually "restores" from the backup whereas the `if` branch copies the file but we still have to recover everything since it was wasn't technically restored. If we set this, this it'll show to users like they don't need to create a backup when they likely do if they're using the copy-file method.

**Review by Tuditi — CHANGES_REQUESTED** [review]
I tried recovering with an old stronghold file and it didn't work. Claiming works however. I get the following error message:
```
{type: 'ClientError', error: '`no password has been supplied, or the key has been cleared from the memory`'}
```

Also I noticed a bug/unhandled error in the restore with stronghold profile flow. After supplying the stronghold password and waiting for the stronghold unlock to expire, the stronghold gets locked and it becomes impossible to create a profile again. Maybe this is somehow related to this? I'll open an issue, since this deserves a separate PR.

**Comment by maxwellmattryan** [comment]
@Tuditi I've tried reproducing the error that you got with old and new strongholds of different coin types - I cannot manage to get the error. Did you have specific steps you took?

**Review by Tuditi — APPROVED** [review]
I didn't manage to reproduce the error myself anymore. Great job! :partying_face:
