### PR TITLE
fix: avoid crash in collectibles gallery

### LINKED ISSUE #7386: [Task]: Fix NFTs gallery crash
### Task description

A user reported that, when Firefly (version 2.1.6) was loading his NFTs, firefly went to a blank screen
image

Scenario:
- more than 200 NFTs
- one of the NFTs looks like https://ipfs.io/ipfs/QmPoYcVm9fx47YXNTkhpMEYSxCD3Bqh7PJYr7eo5YjLgiT

### Requirements

NFT gallery never crasges

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by VmMad**
## Summary

Fixes #7386 
Closes https://github.com/iotaledger/firefly/issues/7389
- Remove extra tag causing lag in `MediaDisplay`
- Handle `Media.play()` Promise correctly before pausing the video
- Bring back previous classes to make the NFT correctly centered and sized
- Virtualize the `CollectiblesGalleryView`
- Reduce IPC calls and async overhead

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

### Instructions

> Please DM me to get more specific instructions.
- Open an account with a lot of collectibles (videos) in the develop branch.
- Compile the app for production in your environment.
- Go to the collectibles tab -> Scroll -> White screen of death.
- Checkout to this branch.
- Compile the app for production in your environment
- Go to the collectibles tab -> Scroll -> Nothing should happen.

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/desktop/views/dashboard/collectibles/views/CollectiblesGalleryView.svelte [hunk 1]
```diff
@@ -4,6 +4,22 @@
     import { localize } from '@core/i18n'
     import { nftSearchTerm, queriedNfts, ownedNfts } from '@core/nfts'
     import { FontWeight, Illustration, Text, SearchInput, NftGalleryItem, Button, ButtonSize } from 'shared/components'
+    import VirtualList from '@sveltejs/svelte-virtual-list'
+    import { onMount } from 'svelte'
+
+    let windowHeight = document.body.clientWidth
```
Comment (begonaalvarezd) [inline packages/desktop/views/dashboard/collectibles/views/CollectiblesGalleryView.svelte:10]: you can use `svelte:window` for this I think and it will make the code a bit cleaner

File: packages/desktop/views/dashboard/collectibles/views/CollectiblesGalleryView.svelte [hunk 2]
```diff
@@ -4,6 +4,22 @@
...
+
+    onMount(() => {
+        function resizeListener() {
+            if (windowHeight !== document.body.clientWidth) {
+                windowHeight = document.body.clientWidth
+            }
+        }
+
+        addEventListener('resize', resizeListener)
```
Comment (begonaalvarezd) [inline packages/desktop/views/dashboard/collectibles/views/CollectiblesGalleryView.svelte:19]: same here, you can attach a resize event to  `svelte:window`
```
<svelte:window on:resize={whatever} />
```

File: packages/desktop/views/dashboard/collectibles/views/CollectiblesGalleryView.svelte [hunk 3]
```diff
@@ -29,15 +68,18 @@
...
-                class="grid overflow-scroll sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5 auto-rows-auto gap-3 2xl:gap-4 pb-1 pr-3 -mr-5"
-            >
-                {#each $queriedNfts as nft}
-                    <NftGalleryItem {nft} />
-                {/each}
-            </div>
+        {#if nftsRows.length}
+            <VirtualList items={nftsRows} let:item>
+                <div
+                    class="grid overflow-scroll sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5 auto-rows-auto gap-3 2xl:gap-4 pb-1 pr-3 -mr-5"
```
Comment (begonaalvarezd) [inline packages/desktop/views/dashboard/collectibles/views/CollectiblesGalleryView.svelte:74]: doesnt the custom cols and rows interact with all this tailwind breakpointss?

File: packages/shared/lib/core/profile/utils/getStorageDirectoryOfProfiles.ts [hunk 4]
```diff
@@ -6,3 +6,11 @@ export const getStorageDirectoryOfProfiles = async (): Promise<string> => {
     const appPath = await Platform.getUserDataPath()
     return `${appPath}/${PROFILE_STORAGE_DIRECTORY}`
 }
+
+export let storageDirectoryOfProfiles = ''
```
Comment (begonaalvarezd) [inline packages/shared/lib/core/profile/utils/getStorageDirectoryOfProfiles.ts:10]: why `getStorageDirectoryOfProfiles` cant be used? I see it used in multiple places in the code, why do we need to change the logic for this specific case?

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

File: packages/desktop/views/dashboard/collectibles/views/CollectiblesGalleryView.svelte (hunk 3 above)
Comment (marc2332) [reply packages/desktop/views/dashboard/collectibles/views/CollectiblesGalleryView.svelte:74]: What do you mean by interact? You mean conflict? If that's the case, no, they don't conflict

**Review by msarcev — APPROVED** [review]
