### PR TITLE
fix: avoid error when trying to burn a token with one decimal

### LINKED ISSUE #7277: [Bug report]: Trying to burn a token with one decimal throws error
### Platform

Desktop

### Version

2.1.4

### Description

When burning a token with one decimal, moving the range slider throws an error. It seems to only happen with one decimal. Two or zero works fine

### Expected behaviour

To just be able to select the amount to burn correctly.

### Actual behaviour

The app throws an error

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Mint a native token with one decimal
2. Go to the assets pane
3. Select the token with one decimal and select burn in the options.
4. Click any part of the range selector. The app will throw an error and you wont be able to change the amount.

### Operating System

Linux

### Diagnostics

_No response_

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

App Version: 2.1.4

platform: linux
platformVersion: 5.19.0-46-generic
platformArchitecture: x64
cpuCount: 8
totalMem: 15755.4 MB
freeMem: 3734.9 MB

Error Type: [Render Context] Error

RangeError: maximumFractionDigits value is out of range.
    at Intl.NumberFormat (<anonymous>)
    at CP (file:///tmp/.mount_firefl1LeLZk/resources/app.asar/public/build/index.js:2:2197890)
    at file:///tmp/.mount_firefl1LeLZk/resources/app.asar/public/build/index.js:2:2665645
    at v (file:///tmp/.mount_firefl1LeLZk/resources/app.asar/public/build/index.js:2:2665674)
    at HTMLElement.g (file:///tmp/.mount_firefl1LeLZk/resources/app.asar/public/build/index.js:2:2666431)

### Error Logs

```shell
Error log is empty
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by VmMad**
## Summary

> Fixes #7277 

...

## Changelog

```
- Make `minimumFractionDigits` take the value of `maximumFractionDigits` if available in case it is undefined.
```

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

> Mint a native token of ´1´ decimal if you don't have one. Click on burn token. Moving the slider should work perfectly fine.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by marc2332 — APPROVED** [review]

**Review by evavirseda — APPROVED** [review]
:rocket: :rocket:

**Review by cpl121 — APPROVED** [review]

File: packages/shared/lib/core/i18n/utils/formatNumber.ts [hunk 1]
```diff
@@ -25,7 +25,7 @@ export function formatNumber(
     const appLanguage = get(appSettings).language
 
     const formatted = Intl.NumberFormat(appLanguage, {
-        minimumFractionDigits: minDecimals ?? 2,
+        minimumFractionDigits: minDecimals ?? maxDecimals ?? 2,
```
Comment (begonaalvarezd) [inline packages/shared/lib/core/i18n/utils/formatNumber.ts:28]: i think this is not 100% accurate, if maxDecimals` was 18 then the new logic means that `minimumFractionDigits` would be 18, and with the old logic it would be 2. If we are going to use maxDecimals, at least I would make a `math.min(maxDecimals,2)` to pick the lowest one. This functions is used in very critical places in the app, we should be cautious

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by begonaalvarezd — APPROVED** [review]
