### PR TITLE
fix: asset selection reactivity in send flow

### LINKED ISSUE #7046: [Task]: Fix asset selection reactivity in send flow
### Task description

In the send form there seems to be a reactivity issue in the asset selection (see the selected asset)

image
image
image
image

### Requirements

Reactivity fixed

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by evavirseda**
## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

Closes #7046 

image

## Changelog

```
- Please write a list of changes
```

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows
-   **Mobile**
    -   [ ] iOS
    -   [ ] Android

### Instructions

- Go to Send asset
- Choose another option from the dropdown

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/components/molecules/AssetIcon.svelte [hunk 1]
```diff
@@ -22,7 +22,7 @@
 
     $: $network, chainId, (chainName = getTooltipText())
     $: isAnimation = asset.id in ANIMATED_TOKEN_IDS
-    switch (asset.id) {
+    $: switch (asset.id) {
```
Comment (begonaalvarezd) [inline packages/shared/components/molecules/AssetIcon.svelte:25]: having such large reactive logic to me is a bit confusing to read, i lose context based on what it triggers
I would make it inside a function

```ts
$: asset, updateAssetIcon()

function updateAssetIcon(): void {
    switch (asset.id) {
        case String(COIN_TYPE[NetworkId.Iota]):
            assetInitials = ''
            assetIconBackgroundColor = '#6E82A4'
            assetIconColor = isBright(assetIconBackgroundColor) ? 'gray-800' : 'white'
            icon = NETWORK_ICON_SVG[NetworkId.Iota]
            break
        case String(COIN_TYPE[NetworkId.Shimmer]):
        case String(COIN_TYPE[NetworkId.Testnet]):
            assetInitials = ''
            assetIconBackgroundColor = '#25DFCA'
            assetIconColor = isBright(assetIconBackgroundColor) ? 'gray-800' : 'white'
            icon = NETWORK_ICON_SVG[NetworkId.Shimmer]
            break
        default:
            assetInitials = getAssetInitials(asset)
            assetIconBackgroundColor = getIconColorFromString(asset.metadata?.name, {
                shades: ['500', '600', '700', '800'],
                colorsToExclude: ['gray'],
            })
            assetIconColor = isBright(assetIconBackgroundColor) ? 'gray-800' : 'white'
            assetLogoUrl = asset.metadata?.standard === TokenStandard.Irc30 ? asset.metadata?.logoUrl ?? '' : ''
            icon = null
    }
}
```

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
left a mini suggestion 🙏🏼

**Review by begonaalvarezd — APPROVED** [review]
🚀
