### PR TITLE
fix: input polishing

### LINKED ISSUE #4457: [Subtask]: Change `amount` placeholder to `0` in amount input

### LINKED ISSUE #4458: [Subtask]: Change `Available balance` to `Balance` in asset amount input

### LINKED ISSUE #4459: [Subtask]: Fix highlight showing on AssetAmountInput + RecipientInput

### LINKED ISSUE #4460: [Subtask]: Fix styling of OptionalInputs

### LINKED ISSUE #4461: [Subtask]: Fix positioning of all input labels

### PR DESCRIPTION
**Pull request by jeeanribeiro**
## Summary
All input polishing tasks included here

## Relevant Issues
- [x] closes #4457
- [x] closes #4458
- [x] closes #4459 
- [x] closes #4460 
- [x] closes #4461

### Platforms
- __Desktop__
  - [ ] MacOS
  - [x] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

## Checklist
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/components/inputs/AssetAmountInput.svelte [hunk 1]
```diff
@@ -105,7 +106,7 @@
         {#if asset}
             <button on:click={onClickAvailableBalance}>
                 <Text color="gray-600" darkColor="gray-500" fontSize="xs" classes="cursor-pointer">
-                    {localize('general.availableBalance', {
+                    {localize('general.balance', {
```
Comment (nicole-obrien) [inline packages/shared/components/inputs/AssetAmountInput.svelte:109]: This doesn't take a value so it is not showing the actual amount next to the word, we might need to just use the general.availableBalance but just change the string. or have a specific locale for here.

**Review by nicole-obrien — CHANGES_REQUESTED** [review]
Just the one change 🙏

File: packages/shared/components/inputs/AssetAmountInput.svelte (hunk 1 above)
Comment (jeeanribeiro) [reply packages/shared/components/inputs/AssetAmountInput.svelte:109]: Didn't catch this at first, now it is fixed, thank you :pray:

**Review by nicole-obrien — APPROVED** [review]
