### PR TITLE
Fix: Leaving dust when sending transaction 

### LINKED ISSUE #7411: [Task]: Insufficient funds error when leaving dust
### Task description

Sending close to entire amount but leaving dust (amount less than minimum required storage deposit) on your address throws "insufficient funds error" when trying to `prepareOutput` in `sendConfirmationPopup`

### Requirements

Dont allow leaving dust in `SendForm`

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by brancoder**
## Summary
- dont allow leaving dust when sending transaction via `SendFormPopup`
-resolves #7411 

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [x] Linux
    -   [ ] Windows

## Checklist

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [x] I have verified that new and existing unit tests pass locally with my changes
-   [x] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/components/inputs/AssetAmountInput.svelte [hunk 1]
```diff
@@ -73,6 +78,8 @@
             error = localize('error.send.amountZero')
         } else if (!bigAmount.mod(1).eq(Big(0))) {
             error = localize('error.send.amountSmallerThanSubunit')
+        } else if (bigAmount && Number(Big(availableBalance)?.minus(bigAmount)) < minRequiredStorageDeposit) {
```
Comment (begonaalvarezd) [inline packages/shared/components/inputs/AssetAmountInput.svelte:81]: This check is not allowing me to send my full amount 🙏🏼

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
Code looks amazing, just left a minor comment 🙏🏼

**Review by begonaalvarezd — COMMENTED** [review]
🚀

**Review by begonaalvarezd — APPROVED** [review]
🚀
