### PR TITLE
fix: address validation error behavior

### LINKED ISSUE #5240: [Task]: Change the way errors are handled at address validation
### Task description

Currently `validateBech32Address` and `validateEthereumAddress` are returning error strings instead of throwing actual errors.

This is problematic, since if for some reason the validate functions are not called, the `error` string will be `undefined` and validation will pass. This should be addressed as follows:

- [x] `validateBech32Address` & `validateEthereumAddress` return booleansif validation passes
- [x] `validateBech32Address` & `validateEthereumAddress` throw errors if validation doesn't pass
- [x] `AliasInput`, `RecipientInput` & `MintNftFormPopup` uses try/catch paradigm to check validation

### Requirements

- https://github.com/iotaledger/firefly/pull/5218

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

### PR DESCRIPTION
**Pull request by maxwellmattryan**
## Summary

> Please summarize your changes, describing __what__ they are and __why__ they were made.

Currently `validateBech32Address` and `validateEthereumAddress` are returning error strings instead of throwing actual errors.

## Changelog

```
- Change address validation functions to return true if valid or throw error if invalid
- Change logic using address validation functions
- Re-organize crypto util module
```

## Relevant Issues

> Please list any related issues using [development keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

Closes #5240 

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [x] Linux
  - [ ] Windows
- __Mobile__
  - [ ] iOS
  - [ ] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

Test recipient address inputs with valid and invalid addresses / strings.

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/components/popups/MintNftFormPopup.svelte [hunk 1]
```diff
@@ -94,7 +98,7 @@
             return
         }
 
-        const isKeysValid = Object.keys(royalties).every((key) => !validateBech32Address($networkHrp, key))
+        const isKeysValid = Object.keys(royalties).every((key) => validateBech32Address($networkHrp, key))
```
Comment (maxwellmattryan) [inline packages/shared/components/popups/MintNftFormPopup.svelte:101]: This logic is duplicated

File: packages/shared/components/inputs/AliasInput.svelte [hunk 2]
```diff
@@ -26,15 +27,18 @@
...
-            return Promise.reject(error)
-        } else if (!isAliasInPossession()) {
-            error = localize('error.aliasMinting.aliasNotInPossession')
+
+        try {
+            validateBech32Address($networkHrp, alias, ADDRESS_TYPE_ALIAS)
+            if (isAliasInPossession()) {
+                return Promise.resolve()
+            } else {
+                error = localize('error.aliasMinting.aliasNotInPossession')
```
Comment (MarkNerdi) [inline packages/shared/components/inputs/AliasInput.svelte:36]: you dont need to assign this value here, because it will be set when catching the error

File: packages/shared/components/popups/MintNftFormPopup.svelte (hunk 1 above)
Comment (Tuditi) [reply packages/shared/components/popups/MintNftFormPopup.svelte]: I created a new issue for this: https://github.com/iotaledger/firefly/issues/5289

File: packages/shared/components/inputs/AliasInput.svelte (hunk 2 above)
Comment (Tuditi) [reply packages/shared/components/inputs/AliasInput.svelte]: I addressed your comment, since Matt is away.

**Review by Tuditi — APPROVED** [review]
Looks good!

File: packages/shared/components/inputs/AliasInput.svelte [hunk 3]
```diff
@@ -22,24 +23,24 @@
...
     }
 
-    function isAliasInPossession(): boolean {
-        return aliasOptions.some((option) => option.value === alias)
+    function validateAliasInPossession(): void {
+        if (aliasOptions.some((option) => option.value === alias)) {
+            return
+        } else {
+            throw new Error(localize('error.aliasMinting.aliasNotInPossession'))
+        }
```
Comment (MarkNerdi) [inline packages/shared/components/inputs/AliasInput.svelte:43]:
```suggestion
    function validateAliasInPossession(): void {
        if (!aliasOptions.some((option) => option.value === alias)) {
            throw new Error(localize('error.aliasMinting.aliasNotInPossession'))
        }
```

we could even put this one right into `validate`

File: packages/shared/components/popups/MintNftFormPopup.svelte [hunk 4]
```diff
@@ -94,11 +98,12 @@
             return
         }
 
-        const isKeysValid = Object.keys(royalties).every((key) => !validateBech32Address($networkHrp, key))
-        if (!isKeysValid) {
+        try {
+            Object.keys(royalties).forEach((key) => validateBech32Address($networkHrp, key))
+        } catch (err) {
             optionalInputErrors.royalties = `Invalid address, must be a valid ${$networkHrp} address where royalties will be sent to.`
-            return
```
Comment (MarkNerdi) [inline packages/shared/components/popups/MintNftFormPopup.svelte:100]: also remove the other `return`s so we get all errors in one go

File: packages/shared/lib/core/nfts/stores/selected-account-nfts.store.ts [hunk 5]
```diff
@@ -1,5 +1,7 @@
-import { selectedAccount } from '@core/account'
 import { derived, Readable } from 'svelte/store'
+
+import { selectedAccount } from '@core/account/stores'
+
```
Comment (MarkNerdi) [inline packages/shared/lib/core/nfts/stores/selected-account-nfts.store.ts:4]: any reasons for the empty lines?

File: packages/shared/lib/core/wallet/actions/activities/generateAndStoreActivitiesForAccount.ts [hunk 6]
```diff
@@ -1,11 +1,13 @@
-import { IAccountState } from '@core/account'
+import { IAccountState } from '@core/account/interfaces'
+
+import { setAccountActivitiesInAllAccountActivities } from '../../stores'
+
```
Comment (MarkNerdi) [inline packages/shared/lib/core/wallet/actions/activities/generateAndStoreActivitiesForAccount.ts:4]: any reasons for the empty lines?

File: packages/shared/lib/core/nfts/utils/parseNftMetadata.ts [hunk 7]
```diff
@@ -57,7 +62,7 @@ function validate(data: IIrc27Metadata): void {
 }
 
 function validateRoyalties(royalties: unknown): void {
-    const isKeysValid = Object.keys(royalties).every((key) => !validateBech32Address(get(networkHrp), key))
+    const isKeysValid = Object.keys(royalties).every((key) => validateBech32Address(get(networkHrp), key))
     if (!isKeysValid) {
         throw `Invalid royalty address, must be a valid ${get(networkHrp)} address where royalties will be sent to.`
     }
```
Comment (MarkNerdi) [inline packages/shared/lib/core/nfts/utils/parseNftMetadata.ts:68]: i think here we need a try catch instead of  `.every` because `validateBech32Address`  wont return any boolean anymore

File: packages/shared/lib/core/layer-2/errors/layer1-recipient.error.ts [hunk 8]
```diff
@@ -0,0 +1,14 @@
...
+    constructor() {
+        const message = localize('error.layer2.layer1Recipient')
+        super({
+            message,
+            showNotification: false,
+            saveToErrorLog: false,
+            logToConsole: true,
+        })
+    }
+}
```
Comment (MarkNerdi) [inline packages/shared/lib/core/layer-2/errors/layer1-recipient.error.ts:14]: why do we need this error class?

File: packages/shared/components/popups/MintNftFormPopup.svelte (hunk 4 above)
Comment (Tuditi) [reply packages/shared/components/popups/MintNftFormPopup.svelte:100]: I actually added a `return` since otherwise it would overwrite the `optionalInputErrors.royalties` string each time. Ideally we should refactor this, so that it throws an error as well, but let's wait until the duplication w/ parseNftMetadata has been removed.

File: packages/shared/lib/core/nfts/stores/selected-account-nfts.store.ts (hunk 5 above)
Comment (Tuditi) [reply packages/shared/lib/core/nfts/stores/selected-account-nfts.store.ts:4]: I think Matt added this, since the import comes from another module

File: packages/shared/lib/core/wallet/actions/activities/generateAndStoreActivitiesForAccount.ts (hunk 6 above)
Comment (Tuditi) [reply packages/shared/lib/core/wallet/actions/activities/generateAndStoreActivitiesForAccount.ts:4]: I guess to signal that this is comming from an outer module.

File: packages/shared/lib/core/layer-2/errors/layer1-recipient.error.ts (hunk 8 above)
Comment (Tuditi) [reply packages/shared/lib/core/layer-2/errors/layer1-recipient.error.ts:14]: Ideally we would have a lot of error classes like this. I added this one specific to remove the duplication here: https://github.com/iotaledger/firefly/blob/38a1c05432452f76ca56bc2f7c83fe1cf8db033b/packages/shared/lib/core/utils/crypto/utils/validateEthereumAddress.ts#L46

**Review by MarkNerdi — APPROVED** [review]
LGTM
