### PR TITLE
fix: swallow receiving on a closed channel error

### LINKED ISSUE #1433: ClientError: {}
### Issue description

When logging out of a profile this error is added to the error log, the

It starts from here https://github.com/iotaledger/firefly/blob/e83c3415deab0b5e25c457a652ef7fd428a158a6/packages/backend/bindings/node/native/src/lib.rs#L62  and the error message is `receiving on a closed channel`
Here https://github.com/iotaledger/firefly/blob/e83c3415deab0b5e25c457a652ef7fd428a158a6/packages/shared/lib/shell/walletApi.ts#L139 it gets converted to this `ClientError` and since the message is only a string, JSON.stringify() removes it

### Firefly version

dev

### OS details

Windows

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Log into a profile
2. Logout
3. Open Error log

### Expected behaviour

There should be no error, the polling should probably stop before or maybe we just ignore this particular error?
Apart from that the error message should be visible

### Actual behaviour

Error is visible in the log, but doesn't really help

### Errors

_No response_

### PR DESCRIPTION
**Pull request by cvarley100**
# Description of change

Due to [the way the poll function is used](https://github.com/iotaledger/firefly/blob/9e136e56a5a16bf4f83b2c32718bd0a440ead02d/packages/backend/bindings/node/index.ts#L72) when sending messages to the backend, poll always returns after destroying the actor. There's no real reason to fundamentally refactor the approach here so we can instead swallow the associated error message.

## Links to any relevant issues

Fixes #1433 

## Type of change

- Fix (a change which fixes an issue)

## How the change has been tested

Tested on Mac dev

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that my latest changes pass CI tests
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/backend/bindings/node/index.ts [hunk 1]
```diff
@@ -89,6 +89,8 @@ export function init(id: string, storagePath?: string): { destroy: () => void; r
     _poll(
         runtime,
         (error, data) => {
+            // Swallow error thrown when poll returns after the actor is destroyed
+            if (error && error.message.includes("receiving on a closed channel")) return
```
Comment (rajivshah3) [inline packages/backend/bindings/node/index.ts:93]:
```suggestion
            if (error && error.message.includes('receiving on a closed channel')) return
```

`prettier` is complaining about the double quotes

**Review by rajivshah3 — APPROVED** [review]
