### PR TITLE
fix: custom mana allotment should send to itself

### LINKED ISSUE #8524: [Task]: custom mana allotment should send itself
### Task description

custom mana allotment should send itself

### PR DESCRIPTION
**Pull request by cpl121**
Closes #8524 

## Summary

> Please summarize your changes, describing **what** they are and **why** they were made.

...

## Changelog

```
- Please write a list of changes
```

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by evavirseda — APPROVED** [review]

**Review by marc2332 — APPROVED** [review]

File: packages/desktop/components/popups/AllotManaPopup.svelte [hunk 1]
```diff
@@ -104,7 +104,7 @@
             const accountId = AddressConverter.parseBech32Address(accountAddress)
             // Send 0 amount transaction to accountAddress with amount in the allotMana
             const prepareOutput = await $selectedWallet.prepareOutput(
-                { recipientAddress: accountAddress, amount: '0' },
+                { recipientAddress: $selectedWallet.depositAddress, amount: '0' },
```
Comment (begonaalvarezd) [inline packages/desktop/components/popups/AllotManaPopup.svelte:107]: This way you are still generating a basic output with a SDRUC, is there no other way to make this so the account gets transitioned and thats all? See the transaction `/alphanet/transaction/0x7b29a68e275e771f4f46e9b7bcde6fa943625c61b919b6155375e13841b79fa427810100`. Sounds like something we could ask the SDK team if they have an idea of how to avoid these random basic outputs with SDRUC

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

File: packages/desktop/components/popups/AllotManaPopup.svelte [hunk 2]
```diff
@@ -34,7 +36,7 @@
         $selectedWallet?.hasConsolidatingOutputsTransactionInProgress || $selectedWallet?.isTransferring
     $: asset = $visibleSelectedWalletAssets[$activeProfile?.network?.id].mana
     $: validAmount = Big(rawAmount ?? 0)?.gt(0)
-    $: accountAddress, validAmount, void preparedOutput()
+    $: accountAddress, validAmount, amount, void preparedAllotMana()
```
Comment (begonaalvarezd) [inline packages/desktop/components/popups/AllotManaPopup.svelte:39]: if you make this based on amount too, you should debounce it otherwise we owuld be bombarding `preparedAllotMana` when using the slider. I suggest to add a debouncer like we have in the delegation popup

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
The wallet crashes in this PR, there are multiple types of errors, with the amount and the recipient 
image

**Review by begonaalvarezd — APPROVED** [review]
