### PR TITLE
fix: pin samsung keyboard and other brands

### LINKED ISSUE #4156: [Task]: Fix Android Samsung keyboard pin entry
# Description

https://discord.com/channels/397872799483428865/996835547484004454/1004532838579830814
Seems Samsung keyboard is having issues with pin component, let's fix it!

### PR DESCRIPTION
**Pull request by amadeu2**
## Summary

This PR fixes an issues with Samsung and others soft-keyboards at enter pin code.
Working on: 
- iOS 15 keyboard 
- Samsung, Huawei, MicrosoftSwiftkey, Motorola and Gboard Android soft-keyboards.

...

## Changelog

```
- Please write a list of changes
```

## Relevant Issues

Closes #4156

### Platforms

> Please select any platforms where your changes have been tested.

- __Desktop__
  - [ ] MacOS
  - [ ] Linux
  - [ ] Windows
- __Mobile__
  - [x] iOS
  - [x] Android

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as intended.

...

## Checklist

> Please tick all of the following boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or modified tests that prove my changes work as intended
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have verified that my latest changes pass CI workflows for testing and linting
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: packages/shared/components/inputs/Pin.svelte [hunk 1]
```diff
@@ -87,18 +84,41 @@
...
     }
+
+    function handleBackspaceMobile(event: KeyboardEvent): void {
+        if (event.key === 'Backspace') {
+            handleBackspace()
+        }
+    }
+
+    function handleNextMobile(i: number): void {
+        if (inputElements[i - 1].value === '') {
```
Comment (begonaalvarezd) [inline packages/shared/components/inputs/Pin.svelte:116]: Im getting a type error here trigger right after the autofocus
```bash
TypeError: Cannot read properties of undefined (reading 'value')
```
Adding optional chaining seems to fix the issue

```suggestion
        if (inputElements[i - 1]?.value === '') {
```

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
To me its working grrreaaat 🚀 

Just left a comment to get rid of an error we get when autofocus triggers

**Review by begonaalvarezd — APPROVED** [review]
lgtm 🚀
